### ISSUE TITLE
Fingerprint for E27 1000 lumen

### ISSUE THREAD

**Issue by knalto** [edvaldeysteinsson/IKEA-Tradfri#6]
Hi Edvald,

Had problems pairing a E27 1000 lumen white bulb, it showed up as Thing and device handlet could not be changed.
Adding the next fingerprint solved the issue for me:

`    fingerprint profileId: "0104", inClusters: "0000, 0003, 0004, 0005, 0006, 0008, 0B05, 1000", outClusters: "0005, 0019, 0020, 1000", manufacturer: "IKEA of Sweden",  model: "TRADFRI bulb E27 W opal 1000lm", deviceJoinName: "TRADFRI bulb E27 W opal 1000lm"
`
Sorry if  this is not the right way, my first contribution ever to the ST/Github world.

Cheers!

**Comment by edvaldeysteinsson** [comment]
Sorry for the late reply and I'm guessing you already sorted this out over at the smartthings community forum but i'll reply anyway, the 1000lm isn't a colour temperature bulb and therefor i see no reason to support it since the build in ZLL Dimmer Bulb or ZigBee Dimmer device types will handle it if you assign any of those to the device.
